version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - "7070:7070"
      - "7443:7443"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.8
      EDDI_JVM_OPTIONS: "-verbose:class -Xlog:gc*=debug:stdout:time,uptime,level -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps/oom.bin"
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 1G
      EDDI_MEMORY_MAX: 1G
      EDDI_JAVA_ENV_TUNE_BUFFER: "jdk.nio.MaxCachedBufferSize=1048576"
      #EDDI_JAVA_ENV_MONGODB_HOST: mongodb.hosts=mongodb
  mongodb:
    image: mongo:3.6
    restart: always
